# TaskLifecycleListener is responsible for the task execution.
spring:
  application.name: task-example
  cloud.task:
    single-instance-enabled: false # only one task with a given task name can be run at a time. Default is false.
    external-execution-id: external-execution-id # External execution id for the task. Default is executionId.
    parent-execution-id: 12345 # Parent execution id for the task. Default is executionId.
    closecontextEnabled: false # Enable/Disable close context on task execution. Default is true.

#  tablePrefix: MY_TASK_ # Prefix for the task tables. Default is TASK_. Not all DB support table prefix!

    initialize-enabled: true # Enable/Disable task tables initialization on startup. Default is true.
#    Only for cases where the task tables are not created yet.


  datasource:
    url: jdbc:h2:mem:mytestdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa

logging.level:
  org:
    springframework:
      cloud:
        task: DEBUG