spring:
  application.name: batch-example
#  batch.initialize-schema: always
  sql.init.schema-locations: classpath:schema-h2.sql

  datasource:
    url: jdbc:h2:mem:mytestdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa

logging.level:
  org:
    springframework:
      cloud:
        task: DEBUG